#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include QMK_KEYBOARD_CONFIG_H

#ifdef RGBLIGHT_ENABLE
#undef RGBLIGHT_SAT_STEP 
#define RGBLIGHT_SAT_STEP 12
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 7
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 7
#define RGBLIGHT_EFFECT_BREATHE_CENTER 1
#endif // RGBLIGHT_ENABLE


#undef PRODUCT
#define PRODUCT         glmxndr - Hacked ErgoDox EZ Shine

#endif


#define PERMISSIVE_HOLD
#undef  MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3
#undef  MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 50

#define RGBLIGHT_COLOR_LAYER_0 0x00,0x88,0x88
#define RGBLIGHT_COLOR_LAYER_1 0x88,0x88,0x00
#define RGBLIGHT_COLOR_LAYER_2 0x88,0x00,0x88
#define RGBLIGHT_COLOR_LAYER_3 0x00,0x00,0x88
#define RGBLIGHT_COLOR_LAYER_4 0x00,0x88,0x00

